version: "3.4"

services:
  # Postgres database
  database:
    hostname: postgres
    image: postgres
    ports:
      - "5432:5432"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - pgData:/var/lib/ocr/data
    environment:
      - PGDATA=/var/lib/ocr/data/pgdata
      # These are for development only, so it's ok that the password is insecure
      - POSTGRES_PASSWORD=ocr
      - POSTGRES_USER=ocr
      - POSTRES_DB=ocr-project
      - DB_HOST=postgresql

  # API server (our code)
  ocr:
    image: credit-ocr
    ports:
      - "8080:8080"
    depends_on:
      - database
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    links:
      - database:postgres
    environment:
      - spring.datasource.username=ocr
      - spring.datasource.password=ocr
      - spring.datasource.url=jdbc:postgresql://postgres:5432/ocr-project



# Create volume to store database
volumes:
  pgData:
